service: service-c
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: /hello
          cors: true

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-my-new-bucket-${self:provider.stage}

  Outputs:
    ServiceCS3Bucket:
      Description: ServiceC S3 bucket
      Value: !Ref NewResource
      Export:
        Name: ServiceCS3Bucket-${self:provider.stage}

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api-dev.ravilearnings.com
    basePath: "v1/service-c" # This will be prefixed to all routes
    stage: ${self:provider.stage}
    certificateName: api-dev.ravilearnings.com
    createRoute53Record: false
    endpointType: regional
