service: service-d
frameworkVersion: "3"

package:
  excludeDevDependencies: false
  artifact: .serverless/service-d.zip

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: /hello
          cors: true

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-my-new-bucket-${self:provider.stage}

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-domain-manager

custom:
  bundle:
    externals: all
  serverless-offline:
    httpPort: 8084
    lambdaPort: 3004
  customDomain:
    domainName: api-dev.ravilearnings.com
    basePath: "v1/service-d" # This will be prefixed to all routes
    stage: ${self:provider.stage}
    certificateName: api-dev.ravilearnings.com
    createRoute53Record: false
    endpointType: regional
