service: service-a
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    environment:
      serviceBS3BucketName:
        Fn::ImportValue: !Sub ServiceBS3Bucket-${self:provider.stage}
      serviceCS3BucketName:
        Fn::ImportValue: !Sub ServiceCS3Bucket-${self:provider.stage}
    events:
      - http:
          method: GET
          path: /hello
          cors: true

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-my-new-bucket-${self:provider.stage}

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api-dev.ravilearnings.com
    basePath: "v1/service-a" # This will be prefixed to all routes
    stage: ${self:provider.stage}
    certificateName: api-dev.ravilearnings.com
    createRoute53Record: false
    endpointType: regional
